name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Change this to 'windows-latest' if you need Windows-specific build steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Unity
        uses: unity-actions/setup@v2
        with:
          unity-version: '2023.1.0f1'  # Change to your Unity version

      - name: Build Project
        run: |
          # Run Unity in batch mode to build your project
          /path/to/Unity/Editor/Unity -batchmode -quit -projectPath . -buildWindowsPlayer "build/YourGame.exe"
          # Replace 'build/YourGame.exe' with your build path and platform
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnityBuild
          path: build/YourGame.exe  # Adjust this path to match your build output

      - name: Auto-merge PR if no conflicts
        id: auto-merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: squash
          commit-message: 'Automatically merged by GitHub Actions'

      - name: Comment on pull request
        if: ${{ steps.auto-merge.outputs.result == 'success' }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"body": "This pull request was automatically merged."}' \
          ${{ github.event.pull_request.comments_url }}
